using System.Diagnostics;
using System.Text;

namespace PhysicsEngine
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Body sun = new(
                    pMass: 1.989e30, 
                    pInitialVelocity: Vector3.Zero,
                    pInitialPosition: Vector3.Zero, 
                    pIsMassive: true, 
                    pIsFixed: true, 
                    pName: "Sun"
                );

            Body earth = new(
                    pMass: 5.972e24,
                    pInitialVelocity : new Vector3(0, 30e3, 0),
                    pInitialPosition: new Vector3(150e9, 0, 0),
                    pIsMassive: true,
                    pIsFixed: false,
                    pName: "Earth"
                );

            Body moon = new(
                    pMass: 0,//7.348e22,
                    pInitialVelocity: new Vector3(0, 30e3 + 1.022e3, 0),
                    pInitialPosition: new Vector3(150e9 + 385e6, 0, 0),
                    pIsMassive: true,
                    pIsFixed: false,
                    pName: "Moon"
                );

            Body iss = new(
                    pMass: 444.615e3,
                    pInitialVelocity: new Vector3(0, 30e3 + 7.66e3, 0),
                    pInitialPosition: new Vector3(150e9 + 6.371e6 + 408e3, 0, 0),
                    pIsMassive: false,
                    pIsFixed: false,
                    pName: "ISS"
                );

            double timeSpan = 365 * 24 * Math.Pow(60, 2);
            double timeResolution = 60;

            Engine simulation = new(timeSpan, timeResolution, new List<Body> { sun, earth, moon, iss });
            simulation.Run();

            //simulation.PrintToScreen();
            simulation.PrintToFile();

            MakePlot("python");
        }

        public static void MakePlot(string cmd, string args="")
        {
            ProcessStartInfo start = new ProcessStartInfo();
            //python interprater location
            start.FileName = @"E:\Programs\Python\Python310\python.exe";
            //argument with file name and input parameters
            start.Arguments = @"E:\Users\thoma\source\repos\OrbitalSimulator\Plotting\plotting.py";
            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = true; // We don't need new window
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
            start.LoadUserProfile = true;
            using (System.Diagnostics.Process process = System.Diagnostics.Process.Start(start))
            {
                using (StreamReader reader = process.StandardOutput)
                {
                    string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
                    string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")
                    Console.WriteLine(result);
                }
            }
        }
    }
}